enum ErrorType
{
    LOCAL_REDEFINITION,
    GLOBAL_REDEFINITION,
    FUNCTION_REDEFINITION,
    TYPE_MISMATCH,
    NON_DECLARED_VARIABLE,
    NON_DECLARED_FUNCTION,
    TOO_FEW_PARAMETERS,
    TOO_MANY_PARAMETERS,
    RETURN_STATEMENT_MISSING
};
